# Generated by Django 5.2.4 on 2025-07-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_marketing_promicional',
            new_name='preco_marketing_promocional',
        ),
    ]
